module.exports = [
    // ========================= BOURSES =========================
    {
      type: "Bourse",
      titre: "Bourse Master Informatique",
      description: "Bourse complète pour étudiants en informatique.",
      image: "https://picsum.photos/400/200",
      logo: "https://picsum.photos/100",
      lienSource: "#",
      lienOrganisation: "#",
      organisme: "Université Paris Saclay",
      orgDescription: "Grande université française",
      eligibility: "Licence en informatique",
      benefits: "Frais + logement",
      language: "French",
      Duration: "2 ans",
      montant: "15000",
      filiere: "Informatique",
      niveau_academique: "Master",
      dateDebut: new Date("2026-09-01"),
      dateLimite: new Date("2026-05-30"),
      pays: "France"
    },
    {
      type: "Bourse",
      titre: "Bourse Doctorat IA",
      description: "Programme doctoral en intelligence artificielle.",
      image: "https://picsum.photos/400/201",
      logo: "https://picsum.photos/101",
      lienSource: "#",
      lienOrganisation: "#",
      organisme: "MIT",
      orgDescription: "Université de recherche",
      eligibility: "Master en IA",
      benefits: "Salaire + logement",
      language: "English",
      Duration: "3 ans",
      montant: "45000",
      filiere: "Intelligence Artificielle",
      niveau_academique: "Doctorat",
      dateDebut: new Date("2026-10-01"),
      dateLimite: new Date("2026-06-15"),
      pays: "USA"
    },
  
    // ========================= EVENEMENTS =========================
    {
      type: "Evenement",
      titre: "Web Dev Conference 2026",
      description: "Conférence internationale de développement web.",
      image: "https://picsum.photos/400/202",
      logo: "https://picsum.photos/102",
      lienSource: "#",
      lienOrganisation: "#",
      organisme: "Web Global",
      orgDescription: "Organisation tech",
      eligibility: "Ouvert à tous",
      benefits: "Certificat & networking",
      language: "English",
      Duration: "3 jours",
      montant: "Free",
      filiere: "Web Development",
      dateDebut: new Date("2026-04-10"),
      dateLimite: new Date("2026-04-10"),
      pays: "Germany",
      lieu: "Berlin"
    },
    {
      type: "Evenement",
      titre: "Data Science Summit",
      description: "Sommet sur la data science et le big data.",
      image: "https://picsum.photos/400/203",
      logo: "https://picsum.photos/103",
      lienSource: "#",
      lienOrganisation: "#",
      organisme: "Data Europe",
      orgDescription: "Data events",
      eligibility: "Professionnels & étudiants",
      benefits: "Conférences & ateliers",
      language: "English",
      Duration: "2 jours",
      montant: "Free",
      filiere: "Data Science",
      dateDebut: new Date("2026-05-20"),
      dateLimite: new Date("2026-05-20"),
      pays: "Spain",
      lieu: "Madrid"
    },
  
    // ========================= FORMATIONS =========================
    {
      type: "Formation",
      titre: "Formation React JS",
      description: "Formation complète React pour débutants.",
      image: "https://picsum.photos/400/204",
      logo: "https://picsum.photos/104",
      lienSource: "#",
      lienOrganisation: "#",
      organisme: "OpenClassrooms",
      orgDescription: "Plateforme e-learning",
      eligibility: "Débutants",
      benefits: "Certificat",
      language: "French",
      Duration: "8 semaines",
      montant: "0",
      filiere: "Web Development",
      mode_apprentissage: "distance",
      statut_financier: "free",
      dateDebut: new Date("2026-03-01"),
      dateLimite: new Date("2026-02-20"),
      pays: "Online"
    },
    {
      type: "Formation",
      titre: "Bootcamp Full Stack",
      description: "Formation intensive Full Stack MERN.",
      image: "https://picsum.photos/400/205",
      logo: "https://picsum.photos/105",
      lienSource: "#",
      lienOrganisation: "#",
      organisme: "Le Wagon",
      orgDescription: "Coding bootcamp",
      eligibility: "Motivation requise",
      benefits: "Diplôme",
      language: "English",
      Duration: "12 semaines",
      montant: "2500",
      filiere: "Full Stack",
      mode_apprentissage: "presentiel",
      statut_financier: "paid",
      dateDebut: new Date("2026-01-15"),
      dateLimite: new Date("2026-01-10"),
      pays: "Morocco"
    },
    {
        type: "Evenement",
        titre: "Game Dev Expo",
        description: "Salon dédié à la création de jeux vidéo.",
        image: "https://source.unsplash.com/800x600/?videogame,gaming,developer",
        logo: "https://source.unsplash.com/200x200/?joystick,game",
        lienSource: "#",
        lienOrganisation: "#",
        organisme: "Indie Games Collective",
        orgDescription: "Association de studios indépendants",
        eligibility: "Passionnés de jeux",
        benefits: "Playtests & Recrutement",
        language: "English",
        Duration: "4 jours",
        montant: "100",
        filiere: "Game Development",
        dateDebut: new Date("2026-11-10"),
        dateLimite: new Date("2026-11-01"),
        pays: "USA",
        lieu: "Moscone Center, 747 Howard St, San Francisco, CA 94103"
      },
    
      // ========================= FORMATION =========================
      {
        type: "Formation",
        titre: "Formation React JS",
        description: "Formation complète React pour débutants.",
        image: "https://source.unsplash.com/800x600/?reactjs,javascript,code",
        logo: "https://source.unsplash.com/200x200/?online,education",
        lienSource: "#",
        lienOrganisation: "#",
        organisme: "OpenClassrooms",
        orgDescription: "Plateforme e-learning",
        eligibility: "Débutants",
        benefits: "Certificat",
        language: "French",
        Duration: "8 semaines",
        montant: "0",
        filiere: "Web Development",
        mode_apprentissage: "distance",
        statut_financier: "free",
        dateDebut: new Date("2026-03-01"),
        dateLimite: new Date("2026-02-20"),
        pays: "Online"
      },
      {
        type: "Formation",
        titre: "Bootcamp DevOps & Cloud",
        description: "Formation intensive DevOps et cloud computing.",
        image: "https://source.unsplash.com/800x600/?cloud-computing,devops,server",
        logo: "https://source.unsplash.com/200x200/?cloud,technology",
        lienSource: "#",
        lienOrganisation: "#",
        organisme: "Cloud Academy",
        orgDescription: "Experts en cloud",
        eligibility: "Développeurs expérimentés",
        benefits: "Certification",
        language: "English",
        Duration: "10 semaines",
        montant: "1800",
        filiere: "DevOps",
        mode_apprentissage: "presentiel",
        statut_financier: "paid",
        dateDebut: new Date("2026-02-10"),
        dateLimite: new Date("2026-02-01"),
        pays: "UK"
      },
      {
        type: "Formation",
        titre: "Data Analytics avec Python",
        description: "Maîtrisez l'analyse de données de A à Z.",
        image: "https://source.unsplash.com/800x600/?python,data,chart",
        logo: "https://source.unsplash.com/200x200/?code,python",
        lienSource: "#",
        lienOrganisation: "#",
        organisme: "DataCamp",
        orgDescription: "Spécialiste Data Science",
        eligibility: "Connaissance basique en Python",
        benefits: "Projets réels",
        language: "English",
        Duration: "12 semaines",
        montant: "300",
        filiere: "Data Science",
        mode_apprentissage: "distance",
        statut_financier: "paid",
        dateDebut: new Date("2026-04-05"),
        dateLimite: new Date("2026-03-25"),
        pays: "Online"
      },
      {
        type: "Formation",
        titre: "Cybersécurité Offensive (Ethical Hacking)",
        description: "Apprenez à sécuriser les systèmes en les testant.",
        image: "https://source.unsplash.com/800x600/?security,hacker,code",
        logo: "https://source.unsplash.com/200x200/?lock,key",
        lienSource: "#",
        lienOrganisation: "#",
        organisme: "Simplon",
        orgDescription: "École inclusive du numérique",
        eligibility: "Demandeurs d'emploi",
        benefits: "Diplôme d'État",
        language: "French",
        Duration: "6 mois",
        montant: "0",
        filiere: "Cybersecurity",
        mode_apprentissage: "presentiel",
        statut_financier: "free",
        dateDebut: new Date("2026-05-01"),
        dateLimite: new Date("2026-03-15"),
        pays: "France"
      },
      {
        type: "Formation",
        titre: "Deep Learning Specialization",
        description: "Formation avancée sur les réseaux de neurones.",
        image: "https://source.unsplash.com/800x600/?neural-network,ai,machine",
        logo: "https://source.unsplash.com/200x200/?deep-learning,ai",
        lienSource: "#",
        lienOrganisation: "#",
        organisme: "DeepLearning.AI",
        orgDescription: "Fondé par Andrew Ng",
        eligibility: "Mathématiques avancées",
        benefits: "Accès à la communauté",
        language: "English",
        Duration: "16 semaines",
        montant: "49/mois",
        filiere: "Intelligence Artificielle",
        mode_apprentissage: "distance",
        statut_financier: "paid",
        dateDebut: new Date("2026-01-15"),
        dateLimite: new Date("2026-01-10"),
        pays: "Online"
      }
  ];
  